config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # General
  root to: 'pages#home'
  get 'knowledge', to: 'pages#knowledge', as: 'knowledge'
  get 'pricing', to: 'pages#pricing', as: 'pricing'
  get 'about', to: 'pages#about', as: 'about'

  # Onboarding
  get 'onboard/pick', to: 'onboard#pick', as: 'pick'
  post 'sprints/new', to: 'sprints#new', as: 'new'
  get 'conversions/new/:id', to: 'conversions#new', as: 'new_conversion'
  post 'conversions/:id', to: 'conversions#create', as: 'conversions'
  get 'onboard/contribute/:id', to: 'onboard#contribute', as: 'contribute'
  patch 'onboard/schedule/:id', to: 'onboard#schedule', as: 'schedule'
  patch 'onboard/complete/:id', to: 'onboard#complete', as: 'complete'

  # Updating
  post 'update/sprint/:id', to: 'update#sprint', as: 'update_sprint'
  post 'update/members/:id', to: 'update#members', as: 'update_members'
  post 'update/lists/:id', to: 'update#lists', as: 'update_lists'
  post 'update/cards/:id', to: 'update#cards', as: 'update_cards'

  # Server side editing contributors
  get 'members/contribute/:id', to: 'members#contribute', as: 'edit_contributors'
  patch 'members/contribute_patch/:id', to: 'members#contribute_patch', as: 'update_contributors'

  # Main
  resources :sprints, except: :new do
    resources :conversions, only: %i[edit update]
    resources :members, only: %i[index edit update]
  end

  # Webhooks
  get 'webhooks', to: 'webhooks#complete'
  post 'webhooks', to: 'webhooks#receive'

  # FRONT END TESTING ENVIRONMENT
  get 'sprints/refresh/:id', to: 'sprints#refresh'
  get 'testing/testing', to: 'testing#testing'
end

app/views/shared/_burndown.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
<div class="chart burndow-chart">
  <canvas id="myChart" width="400" height="200"></canvas>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    We strive for better Sprint management!
  </div>
  <div class="footer-links">
    <a href="https://github.com/mlrcbsousa/trello-project"><i class="fab fa-github"></i></a>
  </div>
</div>

app/views/shared/_meta_tags.html.erb
<title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">
<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />
<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:image:src" content="<%= meta_image %>">
<%= favicon_link_tag 'favicon.ico' %>

app/views/shared/_navbar.html.erb
<div class="wrapper-navbar">
  <div class="navbar-pages">
    <!-- Logo -->
    <%= link_to root_path, id: "logo" do %>
      <%= image_tag "SAlogo.png", height: 50 %>
    <% end %>
    <!-- Right Navigation -->
    <div class="navbar-right hidden-xs hidden-sm">
      <%= link_to "Knowledge", "/knowledge", class: "navbar-item navbar-link" %>
      <%= link_to "Pricing", "/pricing", class: "navbar-item navbar-link" %>
      <%= link_to "About", "/about", class: "navbar-item navbar-link" %>
      <% if user_signed_in? %>
        <!-- Links when logged in -->
        <%= link_to 'My Sprints', sprints_path, class: "navbar-item navbar-link signup-btn" %>
        <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "navbar-item navbar-link" %>
      <% else %>
        <!-- Login link (when logged out) -->
        <%= link_to 'Sign Up', new_user_registration_path, class: "navbar-item navbar-link signup-btn" %>
        <%= link_to 'Log In', new_user_session_path, class: "navbar-item navbar-link" %>
      <% end %>
    </div>
    <div class="navbar-pages-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-pages-dropdown-menu">
          <li><%= link_to "Knowledge", "/knowledge", class: "navbar-item navbar-link" %></li>
          <li><%= link_to "Pricing", "/pricing", class: "navbar-item navbar-link" %></li>
          <li><%= link_to "About", "/about", class: "navbar-item navbar-link" %></li>
          <% if user_signed_in? %>
            <!-- Links when logged in -->
            <li><%= link_to 'My Sprints', sprints_path, class: "navbar-item navbar-link signup-btn" %></li>
            <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "navbar-item navbar-link" %></li>
          <% else %>
            <!-- Login link (when logged out) -->
            <li><%= link_to 'Sign Up', new_user_registration_path, class: "navbar-item navbar-link signup-btn" %></li>
            <li><%= link_to 'Log In', new_user_session_path, class: "navbar-item navbar-link" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_percentage.html.erb
<!-- _percentage.html.erb -->
<p>Base</p>
<div class="bar-base bar-frame iron">
  <div class="bar-content">
    <div class="bar">
      <div class="bar-progress blue"></div>
      <div class="bar-remain dove-gray"></div>
    </div>
    <div class="bar-percent text-center">
      <h4 class="roboto weight-300">70%</h4>
    </div>
  </div>
</div>

<p>Team progress</p>
<div class="bar-base-team bar-frame bar-frame-team iron">
  <div class="bar-content">
    <div class="bar-avatar text-center">
      <img src='https://kitt.lewagon.com/placeholder/users/sisserian' class="avatar avatar-sm"/>
    </div>
    <div class="bar">
      <div class="bar-progress blue"></div>
      <div class="bar-remain dove-gray"></div>
    </div>
    <div class="bar-percent text-center">
      <h2 class="montserrat weight-700">70%</h2>
    </div>
  </div>
</div>

<p>Profile progress</p>
<div class="bar-base-profile bar-frame bar-frame-team iron">
  <div class="bar-content">
    <div class="bar-avatar text-center">
      <img src='https://kitt.lewagon.com/placeholder/users/welan125' class="avatar avatar-md"/>
    </div>
    <div class="bar-subcontent">
      <div class="bar-description">
        <h3 class="montserrat">Chad Braderton</h3>
      </div>
      <div class="bar bar-profile">
        <div class="bar-progress blue"></div>
        <div class="bar-remain dove-gray"></div>
      </div>
    </div>
    <div class="bar-percent text-center">
      <h1 class="montserrat weight-700">70%</h1>
    </div>
  </div>
</div>
<hr>

app/views/shared/_pricing_packages.html.erb
<!--BLOCK ROW START-->
<div class="row">
  <div class="col-md-4">
    <!--PRICE CONTENT START-->
    <div class="generic_content clearfix">
      <!--HEAD PRICE DETAIL START-->
      <div class="generic_head_price clearfix">
        <!--HEAD CONTENT START-->
        <div class="generic_head_content clearfix">
          <!--HEAD START-->
          <div class="head_bg"></div>
          <div class="head">
            <span>Basic</span>
          </div>
          <!--//HEAD END-->
        </div>
        <!--//HEAD CONTENT END-->
        <!--PRICE START-->
        <div class="generic_price_tag clearfix">
          <span class="price">
            <span class="sign"></span>
            <span class="currency">FREE</span>
            <span class="cent"></span>
            <span class="month"></span>
          </span>
        </div>
        <!--//PRICE END-->
      </div>
      <!--//HEAD PRICE DETAIL END-->
      <!--FEATURE LIST START-->
      <div class="generic_feature_list">
        <ul>
          <li><span>20</span> Trello boards</li>
          <li><span>2</span> Members</li>
          <li><span>24/7</span> Support</li>
        </ul>
      </div>
      <!--//FEATURE LIST END-->
      <!--BUTTON START-->
      <div class="generic_price_btn clearfix">
        <a class="" href="/users/sign_up">Sign up</a>
      </div>
      <!--//BUTTON END-->
    </div>
    <!--//PRICE CONTENT END-->
  </div>
  <div class="col-md-4">
    <!--PRICE CONTENT START-->
    <div class="generic_content active clearfix">
      <!--HEAD PRICE DETAIL START-->
      <div class="generic_head_price clearfix">
        <!--HEAD CONTENT START-->
        <div class="generic_head_content clearfix">
          <!--HEAD START-->
          <div class="head_bg"></div>
          <div class="head">
            <span>Standard</span>
          </div>
          <!--//HEAD END-->
        </div>
        <!--//HEAD CONTENT END-->
        <!--PRICE START-->
        <div class="generic_price_tag clearfix">
          <span class="price">
            <span class="sign">€</span>
            <span class="currency">49</span>
            <span class="cent"></span>
            <span class="month">/MON</span>
          </span>
        </div>
        <!--//PRICE END-->
      </div>
      <!--//HEAD PRICE DETAIL END-->
      <!--FEATURE LIST START-->
      <div class="generic_feature_list">
        <ul>
          <li><span>50</span> Trello boards</li>
          <li><span>10</span> Members</li>
          <li><span>24/7</span> Support</li>
        </ul>
      </div>
      <!--//FEATURE LIST END-->
      <!--BUTTON START-->
      <div class="generic_price_btn clearfix">
        <a class="" href="/users/sign_up">Sign up</a>
      </div>
      <!--//BUTTON END-->
    </div>
    <!--//PRICE CONTENT END-->
  </div>
  <div class="col-md-4">
    <!--PRICE CONTENT START-->
    <div class="generic_content clearfix">
      <!--HEAD PRICE DETAIL START-->
      <div class="generic_head_price clearfix">
        <!--HEAD CONTENT START-->
        <div class="generic_head_content clearfix">
          <!--HEAD START-->
          <div class="head_bg"></div>
          <div class="head">
            <span>Unlimited</span>
          </div>
          <!--//HEAD END-->
        </div>
        <!--//HEAD CONTENT END-->
        <!--PRICE START-->
        <div class="generic_price_tag clearfix">
          <span class="price">
            <span class="sign">€</span>
            <span class="currency">99</span>
            <span class="cent"></span>
            <span class="month">/MON</span>
          </span>
        </div>
        <!--//PRICE END-->
      </div>
      <!--//HEAD PRICE DETAIL END-->
      <!--FEATURE LIST START-->
      <div class="generic_feature_list">
        <ul>
          <li><span>Unlimited</span> Trello boards</li>
          <li><span>Unlimited</span> Members</li>
          <li><span>24/7</span> Support</li>
        </ul>
      </div>
      <!--//FEATURE LIST END-->
      <!--BUTTON START-->
      <div class="generic_price_btn clearfix">
        <a class="" href="/users/sign_up">Sign up</a>
      </div>
      <!--//BUTTON END-->
    </div>
    <!--//PRICE CONTENT END-->
  </div>
</div>
<!--//BLOCK ROW END-->

app/views/shared/_sidebar.html.erb
<!-- sidebar -->
<!-- ATTENTION: -->
<!-- This sidebar requires an instance of Sprint to be active  -->
<!-- and saved in the @sprint instance variable -->
<!-- or not and therefore the buttons will be diferent -->
<!-- logic here is tricky so please dnt mess around too much with CSS classes -->
<!-- _js used for javascript id pointing -->
<div id="sidebar">
  <div class="sidebar-top">
    <div class="sidebar-logo">
      <%= link_to root_path do %>
        <%= image_tag "SAlogo-v.png", width: 50 %>
      <% end %>
    </div>
    <div class="sidebar-nav">

      <!-- if sprints index page -->
      <% if current_page?(sprints_path) %>

        <%= link_to pick_path do %>
          <i class="fas fa-plus"></i>
        <% end %>

      <!-- if not sprints index page -->
      <% else %>

        <%= link_to sprints_path do %>
          <i class="fas fa-list"></i>
        <% end %>

        <!-- javascript tabs -->
        <div id="sidebar-tabs_js">
          <!-- SPRINT STATS (sprints/show partial: _sprint_stats)-->
          <%= link_to '#', class: "sidebar-btn_js", id: "sprint-stats-btn_js" do %>
            <i class="fas fa-signal"></i>
          <% end %>
          <!-- TEAM STATS (sprints/show partial: _team_stats)-->
          <%= link_to '#', class: "sidebar-btn_js", id: "team-stats-btn_js" do %>
            <i class="fas fa-users"></i>
          <% end %>
        </div>
        <!-- --------------- end of javascript tabs -->

        <div style="display: flex; flex-direction: column;">
          <!-- TRELLO BOARD -->
          <%= link_to @sprint.trello_url, target: "_blank", class: "sidebar-link-trello" do %>
            <i class="fab fa-trello"></i>
          <% end %>

        </div>

      <% end %>

    </div>
  </div>
  <!-- links to the home pages -->
  <div class="sidebar-bottom">

    <%= link_to "/knowledge" do %>
      <i class="fas fa-book"></i>
    <% end %>
    <%= link_to "/pricing" do %>
      <i class="fas fa-dollar-sign"></i>
    <% end %>
    <%= link_to "/about" do %>
      <i class="fas fa-question"></i>
    <% end %>
    <%= link_to destroy_user_session_path, method: :delete do %>
      <i class="fas fa-sign-out-alt"></i>
    <% end %>
  </div>
</div>

app/views/shared/_stat_card.html.erb
<!-- _stat_card.html.erb -->
<div class="stat-card">
  <div class="stat-main">
    <div class="stat-value">
      <%= stat[:value] %>
    </div>
    <div class="stat-unit">
      <%= stat[:unit] if stat[:unit] %>
    </div>
  </div>
  <div class="stat-description">
    <%= stat[:name] %>
  </div>
</div>

<!-- stat-main danger -->
<!-- stat-main success -->

app/views/shared/_trello_card.html.erb
<!-- _trello_card.html.erb -->
<div class="trello-card">
  <blockquote class="trello-board-compact">
    <a href="<%= type.trello_url %>"><%= type.name %></a>
  </blockquote>
  <!-- <a class="trello-card-overlay" href="#" ></a> -->
</div>