config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # General
  root to: 'pages#home'
  get 'knowledge', to: 'pages#knowledge', as: 'knowledge'
  get 'pricing', to: 'pages#pricing', as: 'pricing'
  get 'about', to: 'pages#about', as: 'about'

  # Onboarding
  get 'onboard/pick', to: 'onboard#pick', as: 'pick'
  post 'sprints/new', to: 'sprints#new', as: 'new'
  get 'conversions/new/:id', to: 'conversions#new', as: 'new_conversion'
  post 'conversions/:id', to: 'conversions#create', as: 'conversions'
  get 'onboard/contribute/:id', to: 'onboard#contribute', as: 'contribute'
  patch 'onboard/schedule/:id', to: 'onboard#schedule', as: 'schedule'
  patch 'onboard/complete/:id', to: 'onboard#complete', as: 'complete'

  # Updating
  post 'update/sprint/:id', to: 'update#sprint', as: 'update_sprint'
  post 'update/members/:id', to: 'update#members', as: 'update_members'
  post 'update/lists/:id', to: 'update#lists', as: 'update_lists'
  post 'update/cards/:id', to: 'update#cards', as: 'update_cards'

  # Server side editing contributors
  get 'members/contribute/:id', to: 'members#contribute', as: 'edit_contributors'
  patch 'members/contribute_patch/:id', to: 'members#contribute_patch', as: 'update_contributors'

  # Main
  resources :sprints, except: :new do
    resources :conversions, only: %i[edit update]
    resources :members, only: %i[index edit update]
  end

  # Webhooks
  get 'webhooks', to: 'webhooks#complete'
  post 'webhooks', to: 'webhooks#receive'

  # FRONT END TESTING ENVIRONMENT
  get 'sprints/refresh/:id', to: 'sprints#refresh'
  get 'testing/testing', to: 'testing#testing'
end

app/models/sprint.rb
class Sprint < ApplicationRecord
  require 'trello'
  belongs_to :user
  belongs_to :webhook, optional: true
  has_many :members, dependent: :destroy
  has_many :lists, dependent: :destroy
  has_many :cards, through: :lists, dependent: :destroy
  has_many :sprint_stats, dependent: :destroy
  has_many :member_stats, through: :members, dependent: :destroy
  has_one :conversion, dependent: :destroy

  # Validations
  validates :start_date, :end_date, :trello_ext_id, :name, presence: true
  # validates_timeliness gem
  # rails generate validates_timeliness:install
  validates_date :end_date, on_or_after: :start_date

  # Callbacks
  after_destroy :delete_webhook

  # --------- Trello webhook
  # Must include the fact that only one webhook will be created per sprint
  # even if more then one user sets up the same board as a sprint on the app
  def delete_webhook
    # find the next sprint using that webhook, and recreate webhook in that sprint.user's name
    # delete webhook if no other sprint is using that webhook
    if webhook
      webhook.sprints.count > 1 ? webhook.sprints.where.not(user: user)[0].post_webhook : webhook.destroy
    end
    user.delete_wh_by_sprint(self)
  end

  def create_webhook
    post_webhook
    # Rails.logger.info "=M=A=D=A=F=U=K=I=N=====W=E=B=H=O=O=K======>>>>>>>>>>>>>> #{response.inspect}"
    update(webhook: Webhook.create!(ext_board_id: trello_ext_id))
  end

  # sends post request for creation of webhook on trello
  def post_webhook
    HTTParty.post(
      "https://api.trello.com/1/tokens/#{user.token}/webhooks/?key=#{ENV['TRELLO_KEY']}",
      query: {
        description: "Sprint webhook user#{user.id}",
        callbackURL: "#{ENV['BASE_URL']}webhooks",
        idModel: trello_ext_id
      },
      headers: { "Content-Type" => "application/json" }
    )
  end

  # ----------
  # helper methods
  def weighted_cards
    cards.where.not(size: :o)
  end

  def contributors
    members.where(contributor: true)
  end

  def ranks
    lists.where.not(rank: 0)
  end

  # call this method after changing any member child schedule
  def update_available_man_hours
    update(available_man_hours: contributors.pluck(:available_hours).sum)
  end

  # STATISTICS
  # integer
  def total_contributors
    contributors.count
  end

  # integer
  def total_days
    (end_date - start_date).to_i
  end

  # integer
  def total_days_from_start
    (Date.today - start_date).to_i
  end

  # integer
  def total_days_to_end
    (end_date - Date.today).to_i
  end

  # integer
  def total_ranks
    lists.where.not(rank: 0).count
  end

  # ------ METRICS ON CARDS ------
  # integer
  def total_cards
    cards.count
  end

  # integer
  def total_cards_done_or_after_done
    ranks[ranks.count - 2].cards.count + ranks.last.cards.count
  end

  # integer
  def total_cards_in_backlog
    ranks[0].cards.count
  end

  # integer
  def total_cards_in_progress
    total_cards - (total_cards_done_or_after_done + total_cards_in_backlog)
  end

  # hash
  def cards_per_size
    cards.group(:size).count
  end

  # integer
  def total_weighted_cards
    cards.where.not(size: :o).count
  end

  # hash
  def weighted_cards_per_size
    weighted_cards.group(:size).count
  end

  # hash
  def weighted_cards_per_rank
    weighted_cards.group(:name).count
  end

  # integer
  def total_story_points
    cards.pluck(:size).map { |size| Card.sizes[size] }.sum
  end

  # only weighted cards, only contributing members
  # hash
  def weighted_cards_per_contributor
    @assigned = weighted_cards.group(:member).count
                              .select { |key, _value| key.contributor if key.respond_to?(:contributor) }
                              .transform_keys(&:full_name)
    @assigned.merge!('Unassigned' => (total_weighted_cards - @assigned.values.sum))
  end

  # only contributing members
  # hash
  def story_points_per_contributor
    assigned = contributors.map { |c| [c.full_name, c.total_story_points] }.to_h
    assigned.merge!('Unassigned' => (total_story_points - assigned.values.sum))
  end

  # hash
  def story_points_per_size
    cards.group(:size).count
         .each_with_object({}) { |(key, value), hash| hash[key] = value * Card.sizes[key] }
         .except('o')
  end

  # hash
  def conversion_per_size
    weighted_cards_per_size.each_with_object({}) { |(k, v), h| h[k] = v * conversion.send(k) }
  end

  # integer
  def total_conversion
    conversion_per_size.values.sum
  end

  # hash of hashes
  def conversion_per_size_per_contributor
    weighted_cards_per_size_per_contributor.transform_values do |value|
      value.each_with_object({}) { |(k, v), h| h[k] = v * conversion.send(k) }
    end
  end

  # for Chartkick
  def conversion_per_size_per_contributor_ck
    conversion_per_size_per_contributor.map { |k, v| { name: k, data: v } }
  end

  # hash of hashes
  def weighted_cards_per_size_per_contributor
    contributors.each_with_object({}) do |contributor, hash|
      hash[contributor.full_name] = contributor.weighted_cards_per_size
    end
  end

  # for Chartkick
  def weighted_cards_per_size_per_contributor_ck
    weighted_cards_per_size_per_contributor.map { |k, v| { name: k, data: v } }
  end

  # ----------------
  # hash
  def conversion_per_contributor
    conversion_per_size_per_contributor.transform_values(&:values).transform_values(&:sum)
  end

  # hash
  def available_hours_per_contributor
    contributors.map { |c| [c.full_name, c.available_hours] }.to_h
  end

  # merge for Chartkick
  def merged_conversion_per_contributor
    [
      { name: 'Allocated', data: conversion_per_contributor },
      { name: 'Available', data: available_hours_per_contributor }
    ]
  end
  # ----------------

  # hash of hashes
  def weighted_cards_per_size_per_rank
    ranks.each_with_object({}) { |rank, hash| hash[rank.name] = rank.weighted_cards_per_size }
  end

  # for Chartkick
  def weighted_cards_per_size_per_rank_ck
    weighted_cards_per_size_per_rank.map { |k, v| { name: k, data: v } }
  end

  # hash of hashes
  def conversion_per_size_per_rank
    weighted_cards_per_size_per_rank.transform_values do |value|
      value.each_with_object({}) { |(k, v), h| h[k] = v * conversion.send(k) }
    end
  end

  # for Chartkick
  def conversion_per_size_per_rank_ck
    conversion_per_size_per_rank.map { |k, v| { name: k, data: v } }
  end

  # ---------------
  # hash of hashes
  def conversion_per_rank
    conversion_per_size_per_rank.transform_values(&:values).transform_values(&:sum)
    # conversion_per_size_per_rank.each_with_object({}) { |(k, v), h| h[k] = v.values.sum }
  end

  def progress_conversion_per_rank
    conversion_per_rank.each_with_object({}) do |(k, v), h|
      h[k] = (v * lists.find_by(name: k).progress_rank).to_i
    end
  end

  # merge for Chartkick
  def merged_conversion_per_rank
    [
      { name: 'Work', data: conversion_per_rank },
      { name: 'Progress', data: progress_conversion_per_rank }
    ]
  end
  # ----------------

  def progress_conversion
    progress_conversion_per_rank.values.sum.to_i
  end

  # decimal (percentage)
  def progress
    progress_data = weighted_cards.map(&:progress).delete_if { |item| item.is_a?(String) }
    total_weighted_cards.zero? ? 0 : (progress_data.sum / total_weighted_cards).round(2)
  end

  # integer
  def story_points_progress
    (progress * total_story_points).to_i
  end

  def stppot
    sprint_stats.map { |s| [s.created_at, (s.total_story_points - s.story_points_progress)] }.to_h
  end

  # not usable by chartkick for some reason
  def stppot_merge_x
    s = sprint_stats.last
    [
      { name: 'Actual', data: stppot },
      {
        name: 'Projection',
        data: {
          s.created_at => (s.total_story_points - s.story_points_progress),
          end_date => 0
        }
      }
    ]
  end

  # actual burndown chart patch used
  def stppot_merge
    s = sprint_stats.last
    stppot.merge(
      s.created_at => (s.total_story_points - s.story_points_progress),
      end_date => 0
    )
  end
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
  before_action :set_sprint, only: %i[show destroy edit update refresh]
  layout 'onboarding', only: %i[new edit]

  def index
    @sprints = current_user.sprints
  end

  def new
    @name = params[:name]
    @trello_ext_id = params[:trello_ext_id]
    @trello_url = params[:trello_url]
    @sprint = Sprint.new
  end

  def show; end

  def refresh
    render 'sprints/_stats_dashboard', sprint: @sprint, layout: false
  end

  def create
    @sprint = Sprint.new(sprint_params)
    @sprint.user = current_user
    if @sprint.save
      # check if that sprint board is already setup in the app by another user
      webhook = Webhook.find_by(ext_board_id: @sprint.trello_ext_id)
      webhook ? @sprint.update(webhook: webhook) : @sprint.create_webhook
      TrelloAPI.new(sprint: @sprint)
      redirect_to new_conversion_path(@sprint)
    else
      render :new, alert: 'Unable to create your sprint!'
    end
  end

  def edit; end

  def update
    @sprint.update(sprint_params)
    if @sprint.save
      Snapshot.new(sprint: @sprint, description: 'sprint edit')
      redirect_to sprints_path, notice: 'Dates were successfully updated.'
    else
      render :edit, alert: 'Unable to update dates.'
    end
  end

  def destroy
    @sprint.destroy
    respond_to do |format|
      format.html { redirect_to sprints_path, notice: 'Sprint was successfully deleted.' }
      format.js
    end
  end

  private

  def set_sprint
    @sprint = Sprint.find(params[:id])
  end

  def sprint_params
    params.require(:sprint).permit(
      :name,
      :trello_url,
      :user_id,
      :start_date,
      :end_date,
      :man_hours,
      :trello_ext_id,
      :webhook_id
    )
  end
end

app/views/sprints/_member_stats.html.erb
<!-- _member_stats.html.erb -->
<div class="member-section hidden" id="member-section_js-<%= member.id%>">
  <div class="row">
    <div class="col-sm-3">
      <div class="member-section-title text-center">
        <h1><%= member.full_name %></h1>
        <strong class="text-primary"><%= member.weighted_cards_count %></strong> cards
      </div>
      <%= render 'shared/stat_card', stat: { value: member.total_conversion, unit: "hrs", name: "Allocated" } %>
      <%= render 'shared/stat_card', stat: { value: member.available_hours, unit: "hrs", name: "Available" } %>
      <div class="member-section-piechart">
        <p>Cards /size</p>
        <%= pie_chart member.weighted_cards_per_size, legend: false, height: "25vh", id: SecureRandom.hex(7) %>
      </div>
    </div>
    <div class="col-sm-9">
      <div class="row">
        <div class="col-sm-6">
          <p>Allocated hours /rank</p>
          <%= bar_chart member.conversion_per_rank, height: "25vh", legend: false, id: SecureRandom.hex(7) %>
        </div>
        <div class="col-sm-6">
          <p>Allocated hours /size</p>
          <%= column_chart member.conversion_per_size, height: "25vh", id: SecureRandom.hex(7) %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-6">
          <p>Cards /size /rank</p>
          <%= bar_chart member.weighted_cards_per_size_per_rank_ck, height: "48vh", legend: false, id: SecureRandom.hex(7) %>
        </div>
        <div class="col-sm-6">
          <p>Allocated work /size /rank</p>
          <%= column_chart member.conversion_per_size_per_rank_ck, height: "48vh", legend: false, id: SecureRandom.hex(7) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sprints/_sprint_stats.html.erb
<!-- _sprint_stats.html.erb -->

<!-- header row -->
<div class="row">
  <div class="col-xs-12">
    <div class="dashboard-title">
      <div class="dashboard-header text-center">
        <h1><%= @sprint.name %></h1>
        <p>Your sprint last <strong><%= @sprint.total_days %> days</strong>: it started <strong><%= @sprint.total_days_from_start %> days</strong> ago. You have reached <strong><%= (@sprint.progress * 100).to_i %> %</strong> of your backlog objectives. You have another <strong><%= @sprint.total_days_to_end %> days left</strong>.</p>
      </div>
      <div class="dashboard-progress">
        <div class="progress">
          <% value = (@sprint.progress * 100).to_i %>
          <div class="progress-bar" role="progressbar" aria-valuenow="<%= value %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= value %>%;">
            <%= value %>%
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- first row with burndown chart -->
<div class="row">

  <div class="col-sm-6">
    <div class="graph-section">
      <%= area_chart @sprint.stppot_merge, stacked: true, height: "33vh", id: SecureRandom.hex(7) %>
      <h5 class="text-center">THE SPRINT BURNDOWN CHART</h5>
    </div>
  </div>
  <!-- 6 cards on right side of burndown chart -->
  <div class="col-sm-6">
    <div class="dashboard-kpis">
      <div class="row">
        <div class="col-sm-3">
          <div class="kpi cards-kpi">
            <div>
              <h2><%= @sprint.total_weighted_cards %></h2>
              <p><i class="fab fa-trello"></i> Weighted Cards</p>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="kpi cards-kpi">
            <div>
              <h2><%= @sprint.total_cards_done_or_after_done %></h2>
              <p><i class="fab fa-trello"></i> Cards completed</p>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="kpi time-kpi">
            <div>
              <h2><%= @sprint.available_man_hours %></h2>
              <p><i class="fas fa-clock"></i> Hours available</p>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="kpi time-kpi">
            <div>
              <h2><%= @sprint.total_conversion %></h2>
              <p><i class="fas fa-clock"></i> Hours planned</p>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-6">
          <div class="graph-section cards-kpi">
            <div>
              <div>
                <%= column_chart @sprint.story_points_per_size, height: "13vh", id: SecureRandom.hex(7) %>
              </div>
              <p>Total story points per size</p>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="graph-section time-kpi">
            <div>
              <div>
                <%= column_chart @sprint.conversion_per_size, height: "13vh", id: SecureRandom.hex(7) %>
              </div>
              <p>Total hours per size</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- second row on main dashboard -->
<div class="graph-section">
  <div class="row text-center">

    <h4>SPRINT STORY POINTS</h4>
    <div class="col-sm-5">
      <div class="text-center">
        <p>Hours /size /rank</p>
        <%= column_chart @sprint.conversion_per_size_per_rank_ck, stacked: true, legend: false, height: "25vh", id: SecureRandom.hex(7) %>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="dashboard-kpis">
        <div class="kpi storypoints-kpi text-center">
          <div>
            <h2><%= @sprint.total_story_points %></h2>
            <p>Total Story points</p>
          </div>
        </div>
        <div class="kpi storypoints-kpi text-center">
          <div>
            <h2><%= @sprint.story_points_progress %></h2>
            <p>Story points completed</p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-5">
      <div class="text-center">
        <p>Weighted cards /size /rank</p>
        <%= column_chart @sprint.weighted_cards_per_size_per_rank_ck, stacked: true, legend: false, height: "25vh", id: SecureRandom.hex(7) %>
      </div>
    </div>

  </div>
</div>

app/views/sprints/_stats_dashboard.html.erb
<!-- _stats_dashboard.html.erb -->
<div class="dashboard">
  <div class="container">
    <div id="sprint-stats_js">
      <!-- SPRINT STATS (sprints/show) partial: _sprint_stats -->
      <%= render 'sprint_stats', sprint: (sprint ||= @sprint) %>
    </div>
    <div id="team-stats_js" class="hidden">
      <!-- TEAM STATS (sprints/show) partial: _team_stats -->
      <%= render 'team_stats', sprint: (sprint ||= @sprint) %>
    </div>
  </div>
</div>

app/views/sprints/_team_stats.html.erb
<!-- _team_stats.html.erb -->

<!-- header row -->
<div class="row">
  <div class="col-xs-12">
    <div class="team-dashboard-title text-center">
        <h1><%= @sprint.name %></h1>
        <p>Your have a total of <strong><%= @sprint.available_man_hours %> hours</strong> man hours available for your sprint. You have planned <strong><%= @sprint.total_conversion %> hours</strong> of work so far.</p>
    </div>
  </div>
</div>

<!-- remaining team stats row -->
<div class="row">
  <!-- main team dashboard -->
  <div class="col-sm-8">
    <!-- whole of team stats -->
    <div id="members-stats_js">
      <div class="row">

        <div class="col-sm-12">
          <div class="graph-section">
            <div class="progress" style="margin-bottom: 5px;">
              <% value = (@sprint.progress * 100).to_i %>
              <div class="progress-bar" role="progressbar" aria-valuenow="<%= value %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= value %>%;">
                <%= value %>%
              </div>
            </div>
          </div>
        </div>

        <div class="col-sm-12">
          <div class="graph-section">
            <%= bar_chart @sprint.merged_conversion_per_contributor, height: "25vh", legend: false, id: SecureRandom.hex(7) %>
            <p>Assigned time vs. time available per contributor</p>
          </div>
        </div>
      </div>
      <div class="row">
        <!-- bottom left side -->

        <div class="col-sm-3">
          <div class="graph-section">
            <%= pie_chart @sprint.weighted_cards_per_size, height: "31vh", donut: true, legend: false, id: SecureRandom.hex(7) %>
            <p>Total number of cards per size</p>
          </div>
        </div>

        <div class="col-sm-3">
          <div class="graph-section">
            <%= pie_chart @sprint.weighted_cards_per_rank, height: "31vh", donut: true, legend: false, id: SecureRandom.hex(7) %>
            <p>Total number of cards per stage</p>
          </div>
        </div>

        <!-- bottom right side -->
        <div class="col-sm-6">

          <div class="graph-section">
            <%= column_chart @sprint.weighted_cards_per_size_per_contributor_ck, height: "13vh", legend: false, id: SecureRandom.hex(7) %>
            <p>Weighted cards /size /member</p>
          </div>

          <div class="graph-section">
            <%= column_chart @sprint.conversion_per_size_per_contributor_ck, height: "13vh", legend: false, id: SecureRandom.hex(7) %>
            <p>Allocated work /size /member</p>
          </div>

        </div>
      </div>
    </div>

    <!-- each members individual stats -->
    <div id="member-stats_js">
      <% @sprint.contributors.each do |member| %>
        <%= render 'member_stats', member: member %>
      <% end %>
    </div>

  </div>

  <!-- left side member list etc -->
  <div class="col-sm-4">

    <div class="row">

      <div class="col-sm-6">
        <div class="graph-section text-center">
          <div>
            <h2>
              <i class="fas fa-user-md"></i>
              <%= @sprint.total_contributors %>
            </h2>
            <p>Total contributor(s)</p>
          </div>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="graph-section text-center">
          <div>
            <h2>
              <i class="fas fa-glasses"></i>
              <%= @sprint.members.count - @sprint.total_contributors %>
            </h2>
            <p>Total observer(s)</p>
          </div>
        </div>
      </div>

      <div class="col-sm-12">

          <div class="graph-section member-cards">
            <!-- member cards -->
            <%= render @sprint.contributors %>
          </div>
      </div>

      <div class="col-sm-12">
        <div class="graph-section">
          <div class="row">
            <div class="col-sm-6">
              <%= column_chart @sprint.story_points_per_size, height: "18vh", id: SecureRandom.hex(7) %>
              <p>Story points /size</p>
            </div>
            <div class="col-sm-6">
              <%= column_chart @sprint.conversion_per_size, height: "18vh", id: SecureRandom.hex(7) %>
              <p>Hours of work /size</p>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/sprints/destroy.js.erb
// app/views/sprints/destroy.js.erb
document.querySelector("[data-sprint-id='<%= @sprint.id %>']")
  .remove();

app/views/sprints/edit.html.erb
<!-- edit.html.erb -->
I WILL PUT THIS FORM IN A MODAL; DNT SPEND TOO MUCH TIME EDITING IT
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3" style="text-align: left;">
      <%= simple_form_for @sprint do |f| %>
        <%= f.input :start_date, as: :string %>
        <%= f.input :end_date, as: :string %>
        <%= f.button :submit, 'Edit my sprint duration', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

app/views/sprints/index.html.erb
<!-- views/sprints/index -->
<div class="container">
  <div class="sprint-list-title text-center">
    <h2>Discover all your Sprints</h2>
    <div class="sprint-list-title-description text-center">
      <p>Select the sprint you want to visualize and discover your stats and progress.</p>
    </div>
  </div>

  <div class="sprint-list">
    <div class="row">
      <% @sprints.each do |sprint| %>
        <div class="col-xs-10 col-md-4 sprint-list-cards" data-sprint-id="<%= sprint.id %>">
            <div class="trello-board text-center">
              <%= render 'shared/trello_card', type: sprint %>
            </div>

            <div class="edits-and-updates">
              <div class="edit">
                <a class="btn btn-default" data-toggle="collapse" href="#collapseEdit<%= sprint.id %>" role="button" aria-expanded="false" aria-controls="collapseEdit<%= sprint.id %>">
                  <h5><i class="fas fa-pencil-alt"></i></h5>
                </a>
              </div>

              <div class="update">
                  <a class="btn btn-default" data-toggle="collapse" href="#collapseUpdate<%= sprint.id %>" role="button" aria-expanded="false" aria-controls="collapseUpdate<%= sprint.id %>">
                    <h5><i class="fas fa-sync-alt"></i></h5>
                  </a>
              </div>
            </div>
            <!-- EDIT COLLAPSE -->
            <div class="collapse" id="collapseEdit<%= sprint.id %>">
              <div class="card card-body">
                <ul>
                  <li>
                    <%= link_to edit_sprint_conversion_path(sprint, sprint.conversion) do %>
                      Edit conversion
                     <% end %>
                  </li>
                  <li>
                    <%= link_to edit_sprint_path(sprint) do %>
                      Edit sprint dates
                    <% end %>
                  </li>
                  <li>
                    <%= link_to edit_contributors_path(sprint) do %>
                      Edit observers and schedule server side
                    <% end %>
                  </li>
                  <li>
                    <%= link_to sprint_members_path(sprint) do %>
                      Edit member schedule server side
                    <% end %>
                  </li>
                </ul>
              </div>
            </div>
            <!-- UPDATE COLLAPSE -->
            <div class="collapse" id="collapseUpdate<%= sprint.id %>">
              <div class="card card-body">
                <ul>
                  <li>
                    <%= link_to update_sprint_path(sprint), method: :post do %>
                      Refresh sprint from trello
                    <% end %>
                  </li>
                  <li>
                    <%= link_to update_members_path(sprint), method: :post do %>
                      Refresh members from trello
                    <% end %>
                  </li>
                  <li>
                    <%= link_to update_lists_path(sprint), method: :post do %>
                      Refresh lists from trello
                    <% end %>
                  </li>
                  <li>
                    <%= link_to update_cards_path(sprint), method: :post do %>
                       Refresh cards from trello
                     <% end %>
                  </li>
                </ul>
              </div>
            </div>

            <div class=" call-to-actions text-center">
              <div class="secondary-call-to-actions">
                <%= link_to sprint.trello_url do %>
                  <h1><i class="fab fa-trello"></i></h1>
                <% end %>
                <%= link_to sprint_path(sprint),
                  remote: true,
                  method: :delete,
                  data: { confirm: "Are you sure?" } do %>
                    <h1><i class="far fa-trash-alt"></i></h1>
                <% end %>
              </div>
              <div>
                <%= link_to 'Visualize my Sprint', sprint_path(sprint), class: "btn btn-warning" %>
              </div>
            </div>
        </div>
      <% end %>
    </div>
  </div>

</div>

<!-- required for the trello card -->
<script src="https://p.trellocdn.com/embed.min.js"></script>

app/views/sprints/new.html.erb
<!-- app/views/sprints/new.html.erb -->
<div class="col-xs-12 col-sm-6">
  <div class="left-side text-center">
    <div class="header text-center">
      <h2>Sprint duration</h2>
      <div class="header-description text-center">
        <p><%= @name %></p>
      </div>
    </div>
    <div id="dates">
      <div class="row">
        <div class="col-xs-6 col-xs-offset-3" style="text-align: left;">
          <%= simple_form_for @sprint do |f| %>
            <%= f.input :start_date, as: :string %>
            <%= f.input :end_date, as: :string %>
            <%= f.input :name, as: :hidden, input_html: { value: @name } %>
            <%= f.input :trello_ext_id, as: :hidden, input_html: { value: @trello_ext_id } %>
            <%= f.input :trello_url, as: :hidden, input_html: { value: @trello_url } %>
            <%= f.button :submit, 'Set my sprint duration', class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="col-xs-12 col-sm-6">
  <div class="right-side duration">
      <div class="illustration" style="background-image: url(<%= image_path('calendar-full.png') %>);">
      </div>
  </div>
<div>

app/views/sprints/show.html.erb
<div id="refresh_show_<%= @sprint.id %>" class="refresh_show">
  <%= render 'stats_dashboard', sprint: @sprint %>
</div>

<!-- JAVASCRIPT HACKY CRACKY TO UPDATE WHICHEVER STATS SECTION I CHOOSE EVERY 5 SECONDS FOR NEW
INFORMATIN FROM THE SERVER -->
<!-- not fully working because of ajax knowledge needed with chartkick and in general with refreshing iniTab function on javascript -->
<script type="text/javascript">
  // const TIMEOUT = 10000;
  const div = document.querySelector(".refresh_show");
  const id = div.id.split('_')[2]
  const poll = () => {
    fetch(`/sprints/refresh/${id}`)
      .then(response => response.text())
      .then((data) => {
        div.innerHTML = ""
        div.insertAdjacentHTML("beforeend", data);
      });
  }
  // setInterval(poll, TIMEOUT);
</script>