config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # General
  root to: 'pages#home'
  get 'knowledge', to: 'pages#knowledge', as: 'knowledge'
  get 'pricing', to: 'pages#pricing', as: 'pricing'
  get 'about', to: 'pages#about', as: 'about'

  # Onboarding
  get 'onboard/pick', to: 'onboard#pick', as: 'pick'
  post 'sprints/new', to: 'sprints#new', as: 'new'
  get 'conversions/new/:id', to: 'conversions#new', as: 'new_conversion'
  post 'conversions/:id', to: 'conversions#create', as: 'conversions'
  get 'onboard/contribute/:id', to: 'onboard#contribute', as: 'contribute'
  patch 'onboard/schedule/:id', to: 'onboard#schedule', as: 'schedule'
  patch 'onboard/complete/:id', to: 'onboard#complete', as: 'complete'

  # Updating
  post 'update/sprint/:id', to: 'update#sprint', as: 'update_sprint'
  post 'update/members/:id', to: 'update#members', as: 'update_members'
  post 'update/lists/:id', to: 'update#lists', as: 'update_lists'
  post 'update/cards/:id', to: 'update#cards', as: 'update_cards'

  # Server side editing contributors
  get 'members/contribute/:id', to: 'members#contribute', as: 'edit_contributors'
  patch 'members/contribute_patch/:id', to: 'members#contribute_patch', as: 'update_contributors'

  # Main
  resources :sprints, except: :new do
    resources :conversions, only: %i[edit update]
    resources :members, only: %i[index edit update]
  end

  # Webhooks
  get 'webhooks', to: 'webhooks#complete'
  post 'webhooks', to: 'webhooks#receive'

  # FRONT END TESTING ENVIRONMENT
  get 'sprints/refresh/:id', to: 'sprints#refresh'
  get 'testing/testing', to: 'testing#testing'
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :sprint
  has_many :cards
  has_many :member_stats, dependent: :destroy

  # Validations
  validates :trello_ext_id, :hours_per_day, presence: true
  # validates :full_name, format: { with: /\A[a-zA-Z ]+\z/, message: "only allows letters" }
  validates :hours_per_day, numericality: true, inclusion: { in: (0..24) }
  # days_per_sprint
  validate :days_per_sprint_less_than_total
  before_validation :days_per_sprint_default
  before_validation :set_available_hours

  # Callbacks
  before_destroy :remove_association_cards

  def remove_association_cards
    cards.each { |card| card.update(member: nil) }
  end
  # before_save :default_values
  # def default_values
  #   self.status ||= 'P' # note self.status = 'P' if self.status.nil? might be safer (per @frontendbeauty)
  # end

  def days_per_sprint_less_than_total
    errors.add(:member, "can't participate more days than the sprint total") if days_per_sprint > sprint.total_days
  end

  def days_per_sprint_default
    self.days_per_sprint = sprint.total_days if days_per_sprint.nil?
  end

  def set_available_hours
    self.available_hours = hours_per_day * days_per_sprint
  end

  def weighted_cards
    cards.where.not(size: :o)
  end

  # STATISTICS
  # integer
  def total_cards
    cards.count
  end

  # ---- to show on member_stats view

  # integer
  def weighted_cards_count
    cards.where.not(size: :o).count
  end

  # hash
  def weighted_cards_per_size
    weighted_cards.group(:size).count
  end

  # hash
  def weighted_cards_per_rank
    weighted_cards.joins(:list).group(:name).count
  end

  # hash of hashes
  def weighted_cards_per_size_per_rank
    weighted_cards.group_by(&:list).each_with_object({}) do |(k, v), h|
      h[k.name] = v.group_by(&:size).transform_values(&:count)
    end
  end

  # for Chartkick
  def weighted_cards_per_size_per_rank_ck
    weighted_cards_per_size_per_rank.map { |k, v| { name: k, data: v } }
  end

  # hash of hashes
  def conversion_per_size_per_rank
    member.weighted_cards_per_size_per_rank.transform_values do |value|
      value.each_with_object({}) { |(k, v), h| h[k] = v * sprint.conversion.send(k) }
    end
  end

  # for Chartkick
  def conversion_per_size_per_rank_ck
    conversion_per_size_per_rank.map { |k, v| { name: k, data: v } }
  end

  # hash
  def conversion_per_size
    weighted_cards_per_size.each_with_object({}) { |(k, v), h| h[k] = v * sprint.conversion.send(k) }
  end

  # hash
  def conversion_per_rank
    conversion_per_size_per_rank.transform_values(&:values).transform_values(&:sum)
    # conversion_per_size_per_rank.each_with_object({}) { |(k, v), h| h[k] = v.values.sum }
  end

  # integer
  # allocated work
  def total_conversion
    weighted_cards.pluck(:size).map { |size| sprint.conversion.send(size) }.sum
  end

  # integer
  def total_story_points
    cards.pluck(:size).map { |size| Card.sizes[size] }.sum
  end

  # float
  def progress
    weighted_cards_count.zero? ? 0 : (weighted_cards.map(&:progress).sum / weighted_cards_count).round(2)
  end

  # integer
  def story_points_progress
    (progress * total_story_points).round(2)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_sprint, only: %i[index edit update]
  before_action :set_sprint_id, only: %i[contribute contribute_patch]
  before_action :set_member, only: %i[edit update]
  layout 'onboarding'

  def index
    @members = @sprint.members.where(contributor: true)
  end

  def edit; end

  def contribute
    @members = @sprint.members.each { |member| member.update(contributor: true) }
  end

  def contribute_patch
    @sprint.members.pluck(:id).each do |id|
      Member.find(id).update(contributor: false) if params[:"contribute-#{id}"]
    end
    redirect_to sprint_members_path(@sprint), notice: "edit your updated member's schedule"
  end

  def schedule
    @members = @sprint.members.where(contributor: true)
  end

  def update
    @member.update(member_params)
    if @member.save
      @sprint.update_available_man_hours
      Snapshot.new(sprint: @sprint, description: 'member edit')
      redirect_to sprints_path, notice: 'member was successfully updated.'
    else
      render :edit, alert: 'Unable to update member.'
    end
  end

  private

  def member_params
    params.require(:member).permit(:contributor, :hours_per_day, :days_per_sprint, :sprint_id)
  end

  def set_member
    @member = Member.find(params[:id])
  end

  def set_sprint_id
    @sprint = Sprint.find(params[:id])
  end

  def set_sprint
    @sprint = Sprint.find(params[:sprint_id])
  end
end

app/views/members/_member.html.erb
<div class="member-card members-cards_js">
  <%= image_tag member.trello_avatar_url, class: "avatar avatar-sm" %>
  <div class="member-card-description">
    <div class="member-card-title">
      <span><%= member.full_name %></span>
      <span>
        <strong class="text-primary"><%= member.story_points_progress.to_i %></strong>
        /<%= member.total_story_points.to_i %> pts
      </span>
    </div>
    <div class="progress">
      <% value = (member.progress * 100).to_i %>
      <div class="progress-bar" role="progressbar" aria-valuenow="<%= value %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= value %>%;">
        <%= value %>%
      </div>
    </div>
  </div>
  <%= link_to "", "#", class: "member-card-link_js", id: "member-card_js-#{member.id}" %>
</div>

app/views/members/config.html.erb
<!-- config.html.erb -->
<%= form_tag labour_path, html: { class: "form-inline" } do %>
  <div class="input-group">
    <%= text_field_tag :query,
      @query,
      class: "form-control",
      placeholder: "hours"
    %>

    <% @members.each do |member| %>
      <%= text_field_tag member.name %>
    <% end %>


  </div>



  <span class="input-group-btn">
    <%= button_tag 'Next', class: "btn btn-default" %>
  </span>
<% end %>

app/views/members/contribute.html.erb
<!-- contribute.html.erb -->
<div class="container">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">

      <%= form_tag update_contributors_path(@sprint), method: :patch do %>
        <div class="observer-list">
          <% @members.each do |member| %>
            <div class="form-group">
              <%= image_tag member.trello_avatar_url, class: "avatar avatar-md" %>
              <%= check_box_tag :"contribute-#{member.id}" %>
              <%= label_tag :"contribute-#{member.id}", member.full_name, class: "control-label" %>
            </div>
          <% end %>
        </div>
        <span class="input-group-btn">
          <%= submit_tag 'Next', class: "btn btn-primary" %>
        </span>
      <% end %>

    </div>
  </div>
</div>

app/views/members/edit.html.erb
<!-- edit.html.erb -->
<%= @member.full_name %>
<%= image_tag @member.trello_avatar_url %>
<%= simple_form_for [@sprint, @member] do |f| %>
  <%= f.input :days_per_sprint %>
  <%= f.input :hours_per_day %>
  <%= f.submit %>
<% end %>

app/views/members/index.html.erb
<!-- index.html.erb -->
select which member's schedule to edit
<% @members.each do |member| %>
  <%= link_to edit_sprint_member_path(member.sprint, member) do %>
    <%= image_tag member.trello_avatar_url %>
  <% end %>
  <%= member.full_name %>
<% end %>

app/views/members/labour.html.erb
<!-- labour.html.erb -->
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>
        <%= @sprint.name %>
      </h1>
      <h3>Contributor schedules</h3>
      <span>days/sprint</span>-
      <span>hours/day</span>
      <%= form_tag sprint_onboard_path(@sprint), method: :patch do %>

        <% @members.each do |member| %>

          <div class="form-group">
            <%= number_field_tag :"days_per_sprint-#{member.id}", @sprint.total_days, in: 1..@sprint.total_days %>
            <%= number_field_tag :"hours_per_day-#{member.id}", 8, in: 1..24 %>
            <%= label_tag :"full_name-#{member.id}", member.full_name, class: "control-label" %>
          </div>

        <% end %>

        <span class="input-group-btn">
          <%= submit_tag 'Complete', class: "btn btn-default" %>
        </span>

      <% end %>
    </div>
  </div>
</div>