config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # General
  root to: 'pages#home'
  get 'knowledge', to: 'pages#knowledge', as: 'knowledge'
  get 'pricing', to: 'pages#pricing', as: 'pricing'
  get 'about', to: 'pages#about', as: 'about'

  # Onboarding
  get 'onboard/pick', to: 'onboard#pick', as: 'pick'
  post 'sprints/new', to: 'sprints#new', as: 'new'
  get 'conversions/new/:id', to: 'conversions#new', as: 'new_conversion'
  post 'conversions/:id', to: 'conversions#create', as: 'conversions'
  get 'onboard/contribute/:id', to: 'onboard#contribute', as: 'contribute'
  patch 'onboard/schedule/:id', to: 'onboard#schedule', as: 'schedule'
  patch 'onboard/complete/:id', to: 'onboard#complete', as: 'complete'

  # Updating
  post 'update/sprint/:id', to: 'update#sprint', as: 'update_sprint'
  post 'update/members/:id', to: 'update#members', as: 'update_members'
  post 'update/lists/:id', to: 'update#lists', as: 'update_lists'
  post 'update/cards/:id', to: 'update#cards', as: 'update_cards'

  # Server side editing contributors
  get 'members/contribute/:id', to: 'members#contribute', as: 'edit_contributors'
  patch 'members/contribute_patch/:id', to: 'members#contribute_patch', as: 'update_contributors'

  # Main
  resources :sprints, except: :new do
    resources :conversions, only: %i[edit update]
    resources :members, only: %i[index edit update]
  end

  # Webhooks
  get 'webhooks', to: 'webhooks#complete'
  post 'webhooks', to: 'webhooks#receive'

  # FRONT END TESTING ENVIRONMENT
  get 'sprints/refresh/:id', to: 'sprints#refresh'
  get 'testing/testing', to: 'testing#testing'
end

app/controllers/onboard_controller.rb
class OnboardController < ApplicationController
  layout 'onboarding'
  before_action :set_sprint, except: :pick

  def pick
    sprints = current_user.sprints.pluck(:trello_ext_id)
    @boards = current_user.boards.where.not(trello_ext_id: sprints)
  end

  def contribute
    @members = @sprint.members
  end

  def schedule
    @sprint.members.pluck(:id).each do |id|
      Member.find(id).update(contributor: false) if params[:"contribute-#{id}"]
    end
    @members = @sprint.members.where(contributor: true)
  end

  def complete
    @sprint.members.pluck(:id).each do |id|
      Member.find(id).update(
        days_per_sprint: params[:"days_per_sprint-#{id}"].to_i,
        hours_per_day: params[:"hours_per_day-#{id}"].to_i
      )
    end
    # update man hours everytime you change labour hours
    @sprint.update_available_man_hours
    Snapshot.new(sprint: @sprint, description: 'first after create')
    redirect_to sprint_path(@sprint), notice: "Successfully created your sprint"
  end

  private

  def set_sprint
    @sprint = Sprint.find(params[:id])
  end
end

app/views/onboard/contribute.html.erb
<!-- contribute.html.erb -->
<div class="col-xs-12 col-sm-6">
  <div class="left-side">
    <div class="header text-center">
      <h2><%= @sprint.name %></h2>
      <div class="header-description text-center">
        <p>Select the members who are considered as observers and not contributors <br>(the actual working team).</p>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <%= form_tag schedule_path(@sprint), method: :patch do %>
        <div class="observer-list">
          <% @members.each do |member| %>
            <div class="form-group">
              <%= image_tag member.trello_avatar_url, class: "avatar avatar-md" %>
              <%= check_box_tag :"contribute-#{member.id}" %>
              <%= label_tag :"contribute-#{member.id}", member.full_name, class: "control-label" %>
            </div>
          <% end %>
        </div>
          <span class="input-group-btn">
            <%= submit_tag 'Next', class: "btn btn-primary" %>
          </span>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="col-xs-12 col-sm-6">
  <div class="right-side contributors">
      <div class="illustration" style="background-image: url(<%= image_path('trelloteam.png') %>);">
      </div>
  </div>
<div>

app/views/onboard/pick.html.erb
<div class="col-xs-12 col-sm-6">
  <div class="left-side">
    <div class="header text-center">
      <h2>Pick your sprint board</h2>
      <div class="header-description text-center">
        <p>Sprint Awesome connects you to your Trello Boards. <br>If you don't have any boards yet, you can copy our template board</p>
      </div>
    </div>

    <div class="pick-up-boards" style="overflow: scroll;">
        <div class="row">
          <% @boards.each do |board| %>
            <div class="col-xs-12 col-sm-6 pick-one-board">
              <div class="trello-card">
                <%= render 'shared/trello_card', type: board %>
                <%= form_tag new_path, method: :post do %>
                  <%= hidden_field_tag :name, board.name %>
                  <%= hidden_field_tag :trello_ext_id, board.trello_ext_id %>
                  <%= hidden_field_tag :trello_url, board.trello_url %>
                  <div class="pick">
                    <%= submit_tag 'Pick this board' %>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
    </div>

  </div>
</div>
<div class="col-xs-12 col-sm-6">
  <div class="right-side pickboard">
      <div class="illustration" style="background-image: url(<%= image_path('pickboard.png') %>);">
      </div>
  </div>
<div>

<!-- required for the trello card -->
<script src="https://p.trellocdn.com/embed.min.js"></script>

app/views/onboard/schedule.html.erb
<!-- schedule.html.erb -->


<div class="col-xs-12 col-sm-6">
  <div class="left-side">
    <div class="header text-center">
      <h2><%= @sprint.name %></h2>
      <div class="header-description text-center">
        <p>Select the total numbers of day per week and hours per day your team members work.</p>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-8 col-xs-offset-2" style="text-align: center;">
        <table width="100%">
          <thead>
            <tr>
              <th style="text-align: center" width="50%"></th>
              <th style="text-align: center" width="25%">days/sprint</th>
              <th style="text-align: center" width="25%">hours/day</th>
            </tr>
          </thead>
          <%= form_tag complete_path(@sprint), method: :patch do %>
          <% @members.each do |member| %>
          <div class="form-group">
            <tbody>
              <tr>
                <td style="text-align: left">
                  <%= image_tag member.trello_avatar_url, class: "avatar avatar-sm" %>
                  <%= label_tag :"full_name-#{member.id}", member.full_name, class: "control-label" %>
                </td>
                <td>
                  <%= number_field_tag :"days_per_sprint-#{member.id}", @sprint.total_days, in: 1..@sprint.total_days %>
                </td>
                <td>
                  <%= number_field_tag :"hours_per_day-#{member.id}", 8, in: 1..24 %>
                </td>
              </tr>
            </div>
            <% end %>
          </tbody>
        </table>

        <div class="input-group-btn">
          <%= submit_tag 'Complete', class: "btn btn-primary schedule-bth"%>
        </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

<div class="col-xs-12 col-sm-6">
  <div class="right-side schedules">
    <div class="illustration" style="background-image: url(<%= image_path('schedule.png') %>);">
    </div>
  </div>
  <div>